My LinkedList
nurcannafi/java-course-turing pull request #2
Opened 2024-10-03 08:16 UTC by nurcannafi

2024-10-03 20:17 UTC, sabuhihuseynov commented on src/main/java/LinkedList/MyLinkedList.java
> +        size++;
if index == 0 it will call method addHead() and inside this method we already increment size

2024-10-03 20:20 UTC, sabuhihuseynov commented on src/main/java/LinkedList/MyLinkedList.java
> +        if (head == null) {
also should check nullability of T object

2024-10-03 20:21 UTC, sabuhihuseynov requested changes
pls look

2024-10-04 07:36 UTC, sabuhihuseynov approved these changes

2024-10-04 07:36 UTC, merged

2024-10-04 15:31 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +    }
why not private???

2024-10-04 15:31 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +public class MyLinkedList<T> {
must be a break line here please!!!

2024-10-04 15:32 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +    MyLinkedList() {
I think this constructor is redundant, wdyt?

2024-10-04 15:38 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +        Node<T> newNode = new Node<T>(value);
why the instance is not `final`?

2024-10-04 15:43 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +    public void addHead(T value) {
why `void`?

2024-10-04 15:46 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +    public void addTail(T value) {
why `void` agaaaaaain?!!!

2024-10-04 16:04 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +    }
You can improve the implementation via using `size` :), anyway lgtm!

2024-10-04 16:05 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +        return data; //silinen deyeri return edir
Allah bu commentin belasini versin!

2024-10-04 16:12 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +            return null;
`Optional.empty()`!!!

2024-10-04 16:13 UTC, elvintaghizade commented on src/main/java/LinkedList/MyLinkedList.java
> +    public T removeHead() {
lets make return type `Optional<T>` :)